language: node_js
node_js:
- 0.12
before_install:
- npm cache clean
- npm install -g grunt-cli bower
- bower install
notifications:
  hipchat:
    rooms:
      secure: dYyzbT01V3v3knkfu7Mvjke1Bdfn+P+udIkV81uK0ctvL1MFba17g24NzAtzY0DWJTHFwom4G9UZibQJnKAkT5e2/8OzaBdLFaFGsWSEetwimrz/rUKQ7QuxcMU5cbBvCwwgiuZ4VTH9lHl822UX2qfklqrjFkzX5PUC+OrkbrnLzrLUKf3Csq9Acj24OLsrwudpBbJnh7RQ6Q8A8wPechJo22l5YYkt9Mms6HkddtkJrF9ycDy380uexgF4UCZiMez5s9SC1g/trF20B6UM6jP8ViR4jQ4cFMHMXwMvHKx9Tw1rQU3xdHOnSCy0XMRPNwiMMzJHS3fckxlMEIawJk92btpmngXojjzaL/u/+AEOeije0CHTcjBZaI2BwR9f5ovKd8SWE91bRZ6J+vhjjwIN26pAVzsv3V9UQvRnjcaiW5C+BjlJykng/2CwSlgVpnoNZ/up/2gPzsmfJfIsLWkiMzDlCiaZ+6ZQgfg1AcFF2yeG6hui05cNWjZGTXzEOjItBXdw471GMD9eMslt614yYn5VXcj2Q3TF+iJelhZa3It9ekGTVaFEksRU3mAAaLsCzYZOYK7sUAcPdO6d5in25QMBgPxRvUSSq71FVWtzh+UxgP+GVzX7OyX3pQohEVstsbiv2ureTdDlY0/B0BqpjyjDgfYGYOAFlwGwazc=
